title: Benefits Of Touching Grass
cuts:
  - start: 0
    end: 0.704
  - start: 6.56
    end: 7.141
  - start: 14.38
    end: 14.7
  - start: 18.125
    end: 18.548
  - start: 25.019
    end: 25.7667
punchInSegments:
  - start: 4.254
    end: 5.053999999999999
    scale: 1.06
  - start: 9.427
    end: 10.309
    scale: 1.06

