titleDurationSec: 5
captionStyle:
  fontFamily: montserrat
  fontSize: 64
  color: "#FFE600"
  y: 1
  animation: fade
  stroke:
    width: 10
    color: "#000000"
  shadow: true
  textTransform: uppercase
  captionsAtATime: 5
  stack: false
  backdrop: none
listicle: true
punchIns: true
emphasis: true
defaultBRollSfx: sfx/realistic/mouse_click.wav
