titleDurationSec: 5
titleStyle:
  fontFamily: montserrat
  fontSize: 68
  color: "#111111"
  y: 0.08
  animation: pop
  stroke: null
  shadow: false
  textTransform: uppercase
  captionsAtATime: 1
  stack: false
  backdrop: box
  fontStyle: normal
  textAlign: center
  backdropColor: "#FFE600"
captionStyle:
  fontFamily: montserrat
  fontSize: 64
  color: "#FFE600"
  y: 1
  animation: fade
  stroke:
    width: 10
    color: "#000000"
  shadow: true
  textTransform: uppercase
  captionsAtATime: 5
  stack: false
  backdrop: none
  fontStyle: normal
  textAlign: center
  backdropColor: null
listicle: true
punchIns: true
emphasis: true
defaultBRollSfx: sfx/realistic/mouse_click.wav
