title: Master Marketing Over Coding
cuts:
  - start: 0
    end: 0.706
  - start: 6.053
    end: 6.363
  - start: 14.277
    end: 14.443
  - start: 17.754
    end: 20.343
  - start: 29.871
    end: 34.72
  - start: 39.287
    end: 45.941
punchInSegments:
  - start: 2.07
    end: 2.994
    scale: 1.12
  - start: 9.294
    end: 10.094000000000001
    scale: 1.06
  - start: 15.445
    end: 16.792
    scale: 1.12
  - start: 27.845
    end: 29.811
    scale: 1.06
  - start: 40.428
    end: 41.374
    scale: 1.12
  - start: 47.566
    end: 48.366
    scale: 1.06
  - start: 50.922
    end: 51.812
    scale: 1.12
listicleOverlay: null
bRolls: []

