title: Asian Guy Glow Up Guide
cuts:
  - start: 0
    end: 1.809
  - start: 40.734994562262095
    end: 40.8667
listicleOverlay:
  start: 4.04
  end: 36.134806960304516
  items:
    - label: Get a perm
      reveal: 4.04
    - label: Go to the gym
      reveal: 13.4
    - label: Drop the glasses
      reveal: 22.5
    - label: Improve your style
      reveal: 26.74
punchInSegments:
  - start: 35.7
    end: 35.922
    scale: 1.12
bRolls: []

