/**
 * Shared SFX/music loudness metadata (LUFS → linear gain).
 * Regenerated by `pnpm audio:loudness` into src/data/audio-loudness.json.
 */

import data from "../../data/audio-loudness.json";

/** Normalize library assets toward this integrated loudness. */
export const AUDIO_LOUDNESS_TARGET_LUFS = -16;

/** Cap post-gain true peak to avoid clipping when boosting quiet files. */
export const AUDIO_LOUDNESS_MAX_TRUE_PEAK_DB = -1;

/** Hard ceiling on boost even when peak headroom allows more. */
export const AUDIO_LOUDNESS_MAX_GAIN = 10;

export type AudioLoudnessEntry = {
  /** Integrated LUFS (EBU R128 / loudnorm input_i). */
  lufs: number;
  /** True peak dBTP. */
  truePeakDb: number;
  /** Linear gain to reach target LUFS, peak-limited. */
  gain: number;
};

export type AudioLoudnessData = {
  targetLufs: number;
  files: Record<string, AudioLoudnessEntry>;
};

const table = data as AudioLoudnessData;

/** Linear gain so `src` plays near the library target LUFS. Missing → 1. */
export function loudnessGainFor(src: string): number {
  const entry = table.files[src];
  if (!entry || !Number.isFinite(entry.gain) || entry.gain <= 0) return 1;
  return entry.gain;
}

/** Gain from measured loudness, limited by true-peak headroom. */
export function gainFromLoudness(
  lufs: number,
  truePeakDb: number,
  targetLufs = AUDIO_LOUDNESS_TARGET_LUFS,
): number {
  if (!Number.isFinite(lufs)) return 1;
  const lufsGain = 10 ** ((targetLufs - lufs) / 20);
  const peakCap = Number.isFinite(truePeakDb)
    ? 10 ** ((AUDIO_LOUDNESS_MAX_TRUE_PEAK_DB - truePeakDb) / 20)
    : AUDIO_LOUDNESS_MAX_GAIN;
  return Math.min(lufsGain, peakCap, AUDIO_LOUDNESS_MAX_GAIN);
}
